### ISSUE TITLE
背景动图改进

### ISSUE THREAD

**Issue by Chen-Zz1** [xinyi-cherry/bit-genshin#1]
背景的动图在登录框之外有一个没有抠干净的鼠标，期待改进
![image](https://github.com/xinyi-cherry/bit-genshin/assets/75784312/227eb2ea-f21a-4152-9622-6e3145ee85ad)

**Comment by xinyi-cherry** [comment]
坏，昨天录屏没盖住（
今天晚上换个图hhhh

**Comment by xinyi-cherry** [comment]
换好了hhhh，不过是白天版（晚上加个夜间版
