### ISSUE TITLE
请求资源文件

### ISSUE THREAD

**Issue by Lingluoluo** [xinyi-cherry/bit-genshin#2]
想要把这个项目移植到自己学校的登录页面，请问可以提供一下资源文件吗，或者可以直接使用里面资源文件的链接吗

**Comment by xinyi-cherry** [comment]
可以直接使用

**Comment by xinyi-cherry** [comment]
> 

但是资源文件建议再找找CDN啥的放一下（kanosaikou.cn那个网址是我的服务器可能负担不起太多请求

**Comment by Lingluoluo** [comment]
好的，但是应该其实也不会有多少人用就是了(
我先用这个链接先开发一下，后续迁移到我自己的服务器上

**Comment by xinyi-cherry** [comment]
OK，字体的引用记得配置跨域CORS
（我懒得翻NGINX配置然后就用PHP传了）
