### ISSUE TITLE
火狐浏览器工作异常

### ISSUE THREAD

**Issue by Chen-Zz1** [xinyi-cherry/bit-genshin#3]
在我的 Windows 下的火狐浏览器无法正常使用登陆界面的交互内容，通过控制台元素查看发现被如下元素遮挡。
![image](https://github.com/xinyi-cherry/bit-genshin/assets/75784312/048f507b-3704-4640-9b17-0ef2cf1fe525)

删除该节点后可以正常点击按钮与文本框，之前使用的 edge 暂未发现异常。

**Comment by xinyi-cherry** [comment]
噢噢我在Edge上弄的，感觉是不同浏览器的兼容问题，这个元素是用来显示一开始的白屏原神图片的，然后在动画结束的时候应该会设置成`display:none`，我看看Firefox咋处理

**Comment by xinyi-cherry** [comment]
已更新
