### ISSUE TITLE
能否修改仓库描述？

### ISSUE THREAD

**Issue by YDX-2147483647** [xinyi-cherry/bit-genshin#4]
```diff
- 原神！启动！ 
+ 原神！启动！ 将你的BIT登录页面修改为原神样式
```

请问能否把仓库描述和 README 同步一下？

原因：我想收录到 https://github.com/YDX-2147483647/best-of-bits ，那边只能自动爬取仓库描述，只有“原神！启动！ ”的话不容易让人明白是什么项目。

**Comment by xinyi-cherry** [comment]
已修改hhhh
